'use client';

import { useEffect, useState } from 'react';
import Link from 'next/link';
import { CandidateListItem, CandidateRecord, parallaxApi } from '../../lib/parallax-api';

export function ProvenanceView() {
  const [candidates, setCandidates] = useState<CandidateListItem[]>([]);
  const [selected, setSelected] = useState('');
  const [record, setRecord] = useState<CandidateRecord | null>(null);
  useEffect(() => { void parallaxApi.listCandidates().then((items) => { setCandidates(items); setSelected(items[0]?.id ?? ''); }); }, []);
  useEffect(() => { if (selected) void parallaxApi.getRecord(selected).then(setRecord); }, [selected]);
  if (!record) return <div className="panel p-8 text-sm text-[var(--muted)]">Loading the source ledger…</div>;
  const epoch = (value: Record<string, unknown>) => ({ observationId: String(value.observation_id ?? 'not recorded'), date: String(value.observation_date ?? value.captured_at_utc ?? `${new Date(record.provenance.sourceCreatedAtUtc).toLocaleDateString()} / generated`), bands: Array.isArray(value.bands) ? value.bands.join(', ') : String(value.band ?? 'synthetic comparison band'), coordinates: String(value.coordinate_frame ?? 'not recorded') });
  const a = epoch(record.provenance.epochA); const b = epoch(record.provenance.epochB);
  return <div className="space-y-5"><div className="flex flex-wrap items-center justify-between gap-4"><select aria-label="Candidate provenance record" value={selected} onChange={(event) => setSelected(event.target.value)} className="border border-[var(--line-strong)] bg-[var(--surface-2)] px-4 py-3 text-sm text-[var(--ink)]">{candidates.map((candidate) => <option key={candidate.id} value={candidate.id}>{candidate.candidateKey}</option>)}</select><span className="mono border border-[var(--line)] px-3 py-2 text-[10px] uppercase tracking-[.12em] text-[var(--amber)]">{record.provenance.datasetType === 'synthetic-demo' ? 'DEMONSTRATION DATASET' : 'VERIFIED EXTERNAL DATA'}</span></div><div className="panel p-6 sm:p-8"><div className="grid gap-8 md:grid-cols-2"><div><p className="eyebrow">Mission / dataset</p><p className="mt-4 text-lg text-[var(--ink)]">{record.provenance.datasetLabel}</p><p className="mt-2 mono text-xs text-[var(--muted)]">{record.provenance.sourceIdentifier}</p><p className="mt-5 text-sm leading-7 text-[var(--muted)]">This record is linked to candidate <span className="text-[var(--ink)]">{record.detail.candidateKey}</span>, processing run <span className="text-[var(--ink)]">{record.detail.processingRunId}</span>, and algorithm <span className="text-[var(--ink)]">{record.provenance.algorithmVersion}</span>.</p></div><div><p className="eyebrow">Processing / generated date</p><p className="mt-4 text-sm leading-7 text-[var(--muted)]">Generated {new Date(record.provenance.sourceCreatedAtUtc).toLocaleString()}<br />Retrieved {record.provenance.retrievalTimestampUtc ? new Date(record.provenance.retrievalTimestampUtc).toLocaleString() : 'not applicable — local demo'}<br />Processing completed {record.provenance.processingCompletedAtUtc ? new Date(record.provenance.processingCompletedAtUtc).toLocaleString() : 'in progress'}</p><p className="mt-5 text-xs leading-6 text-[var(--quiet)]">Source URL / external dataset ID: {record.provenance.datasetType === 'synthetic-demo' ? 'not applicable — generated locally' : record.provenance.sourceIdentifier}</p></div></div><div className="mt-8 grid gap-4 border-t border-[var(--line)] pt-8 md:grid-cols-2"><EpochCard label="Epoch A" data={a} /><EpochCard label="Epoch B" data={b} /></div><div className="mt-8 border-t border-[var(--line)] pt-8"><p className="eyebrow">Processing steps</p><p className="mt-4 text-sm leading-7 text-[var(--muted)]">Registration → photometric normalization → differencing → candidate extraction → measurement and uncertainty → human classification.</p><Link className="mt-5 inline-block text-xs uppercase tracking-[.14em] text-[var(--cyan)]" href={`/candidates/${record.detail.id}`}>Open candidate record →</Link></div></div></div>;
}

function EpochCard({ label, data }: { label: string; data: { observationId: string; date: string; bands: string; coordinates: string } }) { return <div className="border border-[var(--line)] bg-[var(--surface-2)] p-5"><p className="eyebrow">{label}</p><dl className="mt-4 space-y-3 text-xs"><div><dt className="text-[var(--quiet)]">Observation ID</dt><dd className="mt-1 text-[var(--ink)]">{data.observationId}</dd></div><div><dt className="text-[var(--quiet)]">Observation date</dt><dd className="mt-1 text-[var(--ink)]">{data.date}</dd></div><div><dt className="text-[var(--quiet)]">Coordinates / bands</dt><dd className="mt-1 text-[var(--ink)]">{data.coordinates} / {data.bands}</dd></div></dl></div>; }
