import { ArrowDown, ArrowRight } from 'lucide-react';
import { PageIntro } from '../../components/page-intro';
import { RouteFrame } from '../../components/route-frame';

export default function ArchitecturePage() {
  return <RouteFrame marker="system architecture"><PageIntro eyebrow="07 / Architecture" title="A visible chain from observation to human review." body="This is the implemented Phase 7 path. Motion design sits on top of real boundaries; each boundary still preserves the distinction between measured evidence, candidate extraction, and public classification." /><div className="panel p-6 sm:p-10"><div className="flex flex-col items-stretch gap-3 md:flex-row md:items-center"><ArchitectureNode label="Observation Data" detail="epochs + metadata" tone="amber" /><ArrowDown className="mx-auto text-[var(--quiet)] md:hidden" size={18} /><ArrowRight className="hidden text-[var(--quiet)] md:block" size={18} /><ArchitectureNode label="Science Engine" detail="registration + differencing" tone="amber" /><ArrowDown className="mx-auto text-[var(--quiet)] md:hidden" size={18} /><ArrowRight className="hidden text-[var(--quiet)] md:block" size={18} /><ArchitectureNode label="Candidate Extraction" detail="measurements + quality" tone="amber" /><ArrowDown className="mx-auto text-[var(--quiet)] md:hidden" size={18} /><ArrowRight className="hidden text-[var(--quiet)] md:block" size={18} /><ArchitectureNode label="ASP.NET API" detail="contracts + audit" tone="cyan" /><ArrowDown className="mx-auto text-[var(--quiet)] md:hidden" size={18} /><ArrowRight className="hidden text-[var(--quiet)] md:block" size={18} /><ArchitectureNode label="SQL Server" detail="source + run + vote" tone="cyan" /><ArrowDown className="mx-auto text-[var(--quiet)] md:hidden" size={18} /><ArrowRight className="hidden text-[var(--quiet)] md:block" size={18} /><ArchitectureNode label="Web Experience" detail="explore + explain" tone="signal" /><ArrowDown className="mx-auto text-[var(--quiet)] md:hidden" size={18} /><ArrowRight className="hidden text-[var(--quiet)] md:block" size={18} /><ArchitectureNode label="Human Classification" detail="vote + confidence" tone="signal" /></div><p className="mt-10 border-t border-[var(--line)] pt-6 text-sm leading-7 text-[var(--muted)]">Candidate provenance links the processing run to its dataset source. Classification is stored separately, consensus is recalculated by the API, and the passport derives its metrics from those persisted actions.</p></div></RouteFrame>;
}

function ArchitectureNode({ label, detail, tone }: { label: string; detail: string; tone: 'signal' | 'cyan' | 'amber' }) {
  const color = tone === 'signal' ? 'var(--signal)' : tone === 'cyan' ? 'var(--cyan)' : 'var(--amber)';
  return <div className="flex-1 border border-[var(--line)] bg-[var(--surface-2)] p-5" style={{ borderTopColor: color }}><p className="mono text-[10px] uppercase tracking-[.12em]" style={{ color }}>{label}</p><p className="mt-4 text-sm text-[var(--muted)]">{detail}</p></div>;
}
