'use client';

import { AlertTriangle, Check, RefreshCw } from 'lucide-react';
import { useEffect, useState } from 'react';
import { ParallaxApiError, ValidationReport, parallaxApi } from '../../lib/parallax-api';

export function ValidationView() {
  const [report, setReport] = useState<ValidationReport | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);

  async function load() {
    setLoading(true);
    setError(null);
    try {
      setReport(await parallaxApi.getValidation());
    } catch (caught) {
      setError(caught instanceof ParallaxApiError ? caught.message : caught instanceof Error ? caught.message : 'Validation results are unavailable.');
    } finally {
      setLoading(false);
    }
  }

  useEffect(() => { void load(); }, []);

  if (loading) return <div className="panel p-8 text-sm text-[var(--muted)]">Running the measured validation suite…</div>;
  if (error || !report) return <div className="panel p-8"><p className="eyebrow text-[var(--amber)]">Validation unavailable</p><p className="mt-4 text-sm leading-6 text-[var(--muted)]">{error ?? 'No validation report was returned.'}</p><button type="button" onClick={() => void load()} className="focus-ring mt-6 inline-flex items-center gap-2 border border-[var(--line-strong)] px-4 py-3 mono text-[10px] uppercase tracking-[.12em] text-[var(--muted)]"><RefreshCw size={13} /> Retry validation</button></div>;

  return <div className="space-y-6"><div className="flex flex-wrap items-center justify-between gap-4"><span className="mono border border-[var(--amber)]/30 bg-[rgba(243,187,113,.08)] px-3 py-2 text-[10px] uppercase tracking-[.12em] text-[var(--amber)]">{report.dataset_label}</span><button type="button" onClick={() => void load()} className="focus-ring inline-flex items-center gap-2 border border-[var(--line-strong)] px-3 py-2 mono text-[9px] uppercase tracking-[.12em] text-[var(--muted)]"><RefreshCw size={12} /> Run again</button></div><div className="grid gap-4 sm:grid-cols-3"><Metric label="Passed" value={String(report.summary.passed)} tone="signal" /><Metric label="Failed" value={String(report.summary.failed)} tone={report.summary.failed ? 'amber' : 'signal'} /><Metric label="Total cases" value={String(report.summary.total)} tone="cyan" /></div><section className="space-y-3">{report.cases.map((item) => <article key={item.id} className="panel p-5 sm:p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="eyebrow">{item.label}</p><h2 className="mt-3 text-xl font-medium tracking-[-.03em] text-[var(--ink)]">{item.status === 'PASS' ? 'Measured behavior matches the fixture.' : 'Measured behavior needs attention.'}</h2></div><span className={`inline-flex items-center gap-1.5 border px-2.5 py-1 mono text-[9px] uppercase tracking-[.12em] ${item.status === 'PASS' ? 'border-[var(--signal)]/30 bg-[var(--signal-soft)] text-[var(--signal)]' : 'border-[var(--amber)]/30 bg-[rgba(243,187,113,.08)] text-[var(--amber)]'}`}>{item.status === 'PASS' ? <Check size={12} /> : <AlertTriangle size={12} />} {item.status}</span></div><div className="mt-5 grid gap-4 md:grid-cols-3"><Data label="Expected" value={item.expected} /><Data label="Detected" value={item.detected} /><Data label="Error" value={item.error === null ? 'not applicable' : String(item.error)} /></div></article>)}</section><section className="border-t border-[var(--line)] pt-6"><p className="eyebrow">How to read this</p><p className="mt-4 max-w-3xl text-sm leading-7 text-[var(--muted)]">These results are generated by the science service from deterministic synthetic fixtures. They test regression behavior and failure boundaries; they are not a claim of survey completeness, purity, or professional research validation.</p><ul className="mt-4 space-y-2 text-xs leading-6 text-[var(--quiet)]">{report.limitations.map((item) => <li key={item}>· {item}</li>)}</ul></section></div>;
}

function Metric({ label, value, tone }: { label: string; value: string; tone: 'signal' | 'cyan' | 'amber' }) { const color = tone === 'signal' ? 'var(--signal)' : tone === 'cyan' ? 'var(--cyan)' : 'var(--amber)'; return <div className="panel p-5" style={{ borderTopColor: color }}><p className="mono text-[9px] uppercase tracking-[.12em] text-[var(--quiet)]">{label}</p><p className="mt-3 text-3xl font-medium" style={{ color }}>{value}</p></div>; }
function Data({ label, value }: { label: string; value: string }) { return <div className="border border-[var(--line)] bg-[var(--surface-2)] p-4"><p className="mono text-[9px] uppercase tracking-[.1em] text-[var(--quiet)]">{label}</p><p className="mt-3 text-sm leading-6 text-[var(--muted)]">{value}</p></div>; }
